name: CI tests

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "24"

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run unit tests and checks
        run: ./gradlew check

      - name: Report check results on PR
        if: ${{ github.event_name == 'pull_request' && !cancelled() }}
        uses: dorny/test-reporter@v2
        with:
          name: Gradle Checks
          path: lib/build/test-results/test/*.xml
          reporter: java-junit
          only-summary: "false"
